version: '3.9'


services:
  db:
    env_file: 
      - db.env
      - common.env
    expose:
      - 3306
    image: mysql:8.0.25
    ports:
      - target: 3306
        published: $MYSQL_PORT
        protocol: tcp
        mode: host
    restart: always


  pma:
    depends_on: 
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD:
        $MYSQL_ROOT_PASSWORD
    env_file:
      - common.env
    image: phpmyadmin:5.1.1
    ports:
      - target: 80
        published: $PMA_PORT
        protocol: tcp
        mode: host
    restart: always


  scrape:
    build:
      context: 
        $ROOT/scrape/env/
      dockerfile:
        docker/Dockerfile
    depends_on: 
      - db
    env_file:
      common.env
    image: 
      kagemeka/anikore-scrape
    tty: true
    volumes:
      - type: bind
        source: $ROOT/scrape/
        target: /root/scrape/
        volume:
          nocopy: true



    
